import React from "react";
import { motion } from "framer-motion";
import {
  FileText,
  ShieldCheck,
  UserCheck,
  Scale,
  AlertTriangle,
  Gavel,
  Sparkles,
  CheckCircle2,
} from "lucide-react";

const TermsAndConditions = () => {

  const logoSrc = "/IMG/Logo.jpg";

  // =========================================================
  // INTRODUCTION CONTENT
  // =========================================================

  const introduction = [
    {
      icon: <FileText />,
      text: (
        <>
          This document is an electronic record in terms of Information
          Technology Act, 2000 and rules there under as applicable and the
          amended provisions pertaining to electronic records in various
          statutes as amended by the Information Technology Act, 2000. This
          electronic record is generated by a computer system and does not
          require any physical or digital signatures.
        </>
      ),
    },

    {
      icon: <ShieldCheck />,
      text: (
        <>
          This document is published in accordance with the provisions of
          Rule 3 (1) of the Information Technology (Intermediaries guidelines)
          Rules, 2011 that require publishing the rules and regulations,
          privacy policy and Terms of Use for access or usage of domain name{" "}
          <strong>www.pomwb.com</strong> (“Website”), including the related
          mobile site and mobile application (hereinafter referred to as
          “Platform”).
        </>
      ),
    },

    {
      icon: <Scale />,
      text: (
        <>
          The Platform is owned by <strong>POMWB</strong>, a company
          incorporated under the Companies Act, 1956 with its registered
          office at{" "}
          <strong>
            Nilkuthidanga, Puruli, West Bengal, 723101
          </strong>{" "}
          (hereinafter referred to as "Platform Owner", “we”, “us”, “our”).
          This website is operated by{" "}
          <strong>Piyali Sarkar Bakshi</strong>, and the Bank Account Name is{" "}
          <strong>Piyali Sarkar Bakshi</strong>.
        </>
      ),
    },

    {
      icon: <UserCheck />,
      text: (
        <>
          Your use of the Platform and services and tools are governed by the
          following terms and conditions ("Terms of Use") as applicable to the
          Platform including the applicable policies which are incorporated
          herein by way of reference. If You transact on the Platform, You
          shall be subject to the policies that are applicable to the Platform
          for such transaction. By mere use of the Platform, You shall be
          contracting with the Platform Owner and these terms and conditions
          including the policies constitute Your binding obligations, with
          Platform Owner.
        </>
      ),
    },

    {
      icon: <FileText />,
      text: (
        <>
          These Terms of Use relate to your use of our website, goods (as
          applicable) or services (as applicable) (collectively, “Services”).
          Any terms and conditions proposed by You which are in addition to or
          which conflict with these Terms of Use are expressly rejected by the
          Platform Owner and shall be of no force or effect. These Terms of
          Use can be modified at any time without assigning any reason. It is
          your responsibility to periodically review these Terms of Use to stay
          informed of updates.
        </>
      ),
    },

    {
      icon: <UserCheck />,
      text: (
        <>
          For the purpose of these Terms of Use, wherever the context so
          requires "you", “your” or "user" shall mean any natural or legal
          person who has agreed to become a user/buyer on the Platform.
        </>
      ),
    },
  ];

  // =========================================================
  // TERMS LIST
  // =========================================================

  const termsList = [
    "To access and use the Services, you agree to provide true, accurate and complete information to us during and after registration, and you shall be responsible for all acts done through the use of your registered account on the Platform.",

    "Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials offered on this website or through the Services, for any specific purpose. You acknowledge that such information and materials may contain inaccuracies or errors and we expressly exclude liability for such inaccuracies or errors to the fullest extent permitted by law.",

    "Your use of our Services and the Platform is solely and entirely at your own risk and discretion for which we shall not be liable to you in any manner. You are required to independently assess and ensure that the Services meet your requirements.",

    "The contents of the Platform and the Services are proprietary to us and are licensed to us. You will not have any authority to claim any intellectual property rights, title, or interest in its contents. The contents includes and is not limited to the design, layout, look and graphics.",

    "You acknowledge that unauthorized use of the Platform and/or the Services may lead to action against you as per these Terms of Use and/or applicable laws.",

    "You agree to pay us the charges associated with availing the Services.",

    "You agree not to use the Platform and/ or Services for any purpose that is unlawful, illegal or forbidden by these Terms, or Indian or local laws that might apply to you.",

    "You agree and acknowledge that website and the Services may contain links to other third party websites. On accessing these links, you will be governed by the terms of use, privacy policy and such other policies of such third party websites. These links are provided for your convenience for provide further information.",

    "You understand that upon initiating a transaction for availing the Services you are entering into a legally binding and enforceable contract with the Platform Owner for the Services.",

    "You shall indemnify and hold harmless Platform Owner, its affiliates, group companies (as applicable) and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorneys’ fees, made by any third party or penalty imposed due to or arising out of Your breach of this Terms of Use, privacy Policy and other Policies, or Your violation of any law, rules or regulations or the rights (including infringement of intellectual property rights) of a third party.",

    "In no event will the Platform Owner be liable for any indirect, consequential, incidental, special or punitive damages, including without limitation damages for loss of profits or revenues, business interruption, loss of business opportunities, loss of data or loss of other economic interests, whether in contract, negligence, tort or otherwise, arising from the use of or inability to use the Services, however caused and whether arising in contract, tort, negligence, warranty or otherwise, exceed the amount paid by You for using the Services giving rise to the cause of action or Rupees One Hundred (Rs. 100) whichever is less.",

    "Notwithstanding anything contained in these Terms of Use, the parties shall not be liable for any failure to perform an obligation under these Terms if performance is prevented or delayed by a force majeure event.",

    "These Terms and any dispute or claim relating to it, or its enforceability, shall be governed by and construed in accordance with the laws of India.",

    "All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in puruli,West bengal.",

    "All concerns or communications relating to these Terms must be communicated to us using the contact information provided on this website.",
  ];

  // =========================================================
  // ANIMATION
  // =========================================================

  const cardVariants = {
    hidden: {
      opacity: 0,
      y: 35,
    },

    visible: {
      opacity: 1,
      y: 0,
      transition: {
        duration: 0.55,
        ease: "easeOut",
      },
    },
  };

  return (
    <main
      className="
        min-h-screen
        overflow-hidden
        bg-[#f8f4eb]
        text-[#3f1616]
      "
    >
      {/* =====================================================
          HERO
      ===================================================== */}

      <section
        className="
          relative
          px-4
          pt-10
          pb-10
          sm:pt-14
          sm:pb-14
          lg:pt-16
        "
      >
        {/* Decorative background glow */}

        <div
          className="
            pointer-events-none
            absolute
            left-1/2
            top-0
            -translate-x-1/2
            w-[280px]
            h-[180px]
            sm:w-[480px]
            sm:h-[240px]
            rounded-full
            bg-[#d4ad54]/10
            blur-3xl
          "
        />

        {/* Decorative circles */}

        <motion.div
          animate={{
            rotate: [0, 45, 90, 45, 0],
          }}
          transition={{
            duration: 18,
            repeat: Infinity,
            ease: "easeInOut",
          }}
          className="
            pointer-events-none
            absolute
            left-5
            top-20
            hidden
            lg:block
            h-20
            w-20
            border
            border-[#d4ad54]/20
          "
        />

        <motion.div
          animate={{
            rotate: [0, -30, -60, -30, 0],
          }}
          transition={{
            duration: 20,
            repeat: Infinity,
            ease: "easeInOut",
          }}
          className="
            pointer-events-none
            absolute
            right-8
            top-24
            hidden
            lg:block
            h-24
            w-24
            rounded-full
            border
            border-[#741522]/10
          "
        />

        <div
          className="
            relative
            z-10
            mx-auto
            max-w-5xl
            text-center
          "
        >
          {/* Small label */}

          <motion.p
            initial={{
              opacity: 0,
              y: 15,
            }}
            animate={{
              opacity: 1,
              y: 0,
            }}
            transition={{
              duration: 0.5,
            }}
            className="
              mb-3
              text-[8px]
              uppercase
              tracking-[0.42em]
              text-[#977e73]
              sm:text-[9px]
            "
          >
            Darsh · Legal Information
          </motion.p>

          {/* =================================================
              DARSH LOGO
          ================================================= */}

          <motion.div
            initial={{
              opacity: 0,
              scale: 0.82,
              y: 12,
            }}
            animate={{
              opacity: 1,
              scale: 1,
              y: 0,
            }}
            transition={{
              duration: 0.8,
              delay: 0.12,
              ease: "easeOut",
            }}
            className="
              mx-auto
              mb-5
              flex
              items-center
              justify-center
            "
          >
            <div
              className="
                relative
                flex
                h-[82px]
                w-[82px]
                items-center
                justify-center
                rounded-full
                border
                border-[#c9a24a]
                bg-[#fffdf8]
                p-2
                shadow-[0_8px_30px_rgba(116,21,34,0.10)]
                sm:h-[100px]
                sm:w-[100px]
                sm:p-2.5
              "
            >
              {/* Inner gold ring */}

              <div
                className="
                  absolute
                  inset-1.5
                  rounded-full
                  border
                  border-[#c9a24a]/30
                  sm:inset-2
                "
              />

              {/* Logo */}

              <img
                src={logoSrc}
                alt="Darsh"
                className="
                  relative
                  z-10
                  h-full
                  w-full
                  rounded-full
                  object-contain
                  p-1
                  sm:p-2
                "
                onError={(e) => {
                  e.currentTarget.style.display = "none";
                }}
              />

              {/* Small decorative sparkle */}

              <Sparkles
                className="
                  absolute
                  -right-1
                  -top-1
                  h-4
                  w-4
                  text-[#c9a24a]
                  sm:h-5
                  sm:w-5
                "
                strokeWidth={1.2}
              />
            </div>
          </motion.div>

          {/* Decorative divider */}

          <motion.div
            initial={{
              opacity: 0,
              scaleX: 0,
            }}
            animate={{
              opacity: 1,
              scaleX: 1,
            }}
            transition={{
              duration: 0.7,
              delay: 0.25,
            }}
            className="
              mb-5
              flex
              items-center
              justify-center
              gap-3
            "
          >
            <span className="h-px w-10 bg-[#c9a24a] sm:w-16" />

            <Sparkles
              className="
                h-4
                w-4
                text-[#c9a24a]
              "
              strokeWidth={1.3}
            />

            <span className="h-px w-10 bg-[#c9a24a] sm:w-16" />
          </motion.div>

          {/* Heading */}

          <motion.h1
            initial={{
              opacity: 0,
              y: 25,
            }}
            animate={{
              opacity: 1,
              y: 0,
            }}
            transition={{
              duration: 0.7,
              delay: 0.3,
            }}
            className="
              font-serif
              text-4xl
              font-normal
              leading-tight
              tracking-[-0.02em]
              text-[#351216]
              sm:text-5xl
              md:text-6xl
            "
          >
            Terms & Conditions
          </motion.h1>

          <motion.p
            initial={{
              opacity: 0,
              y: 15,
            }}
            animate={{
              opacity: 1,
              y: 0,
            }}
            transition={{
              duration: 0.6,
              delay: 0.42,
            }}
            className="
              mx-auto
              mt-5
              max-w-2xl
              text-sm
              leading-7
              text-[#806c63]
              sm:text-base
            "
          >
            Please read these terms carefully before accessing,
            browsing or using the Darsh platform and services.
          </motion.p>
        </div>
      </section>

      {/* =====================================================
          IMPORTANT NOTICE
      ===================================================== */}

      <section className="px-4 pb-8">
        <motion.div
          initial={{
            opacity: 0,
            y: 20,
          }}
          animate={{
            opacity: 1,
            y: 0,
          }}
          transition={{
            duration: 0.6,
            delay: 0.5,
          }}
          className="
            relative
            mx-auto
            max-w-5xl
            overflow-hidden
            bg-[#5d0e16]
            p-5
            text-[#f8f3e9]
            shadow-[0_15px_40px_rgba(89,50,40,0.14)]
            sm:p-7
          "
        >
          {/* Decoration */}

          <div
            className="
              pointer-events-none
              absolute
              -right-12
              -top-12
              h-32
              w-32
              rounded-full
              border
              border-[#c9a24a]/20
            "
          />

          <div className="relative z-10 flex items-start gap-4">
            <div
              className="
                flex
                h-11
                w-11
                flex-shrink-0
                items-center
                justify-center
                border
                border-[#c9a24a]/50
                text-[#c9a24a]
              "
            >
              <AlertTriangle
                className="h-5 w-5"
                strokeWidth={1.5}
              />
            </div>

            <div>
              <p
                className="
                  mb-1
                  text-[9px]
                  uppercase
                  tracking-[0.25em]
                  text-[#c9a24a]
                "
              >
                Important
              </p>

              <p
                className="
                  text-sm
                  leading-6
                  text-[#f3e9dd]
                  sm:text-base
                "
              >
                ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM
                INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS
                UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE
                CAREFULLY BEFORE PROCEEDING.
              </p>
            </div>
          </div>
        </motion.div>
      </section>

      {/* =====================================================
          INTRODUCTION
      ===================================================== */}

      <section className="px-4 pb-12">
        <div className="mx-auto max-w-5xl">
          <motion.div
            initial="hidden"
            whileInView="visible"
            viewport={{
              once: true,
              amount: 0.08,
            }}
            variants={{
              hidden: {},
              visible: {
                transition: {
                  staggerChildren: 0.08,
                },
              },
            }}
            className="space-y-5"
          >
            {introduction.map((item, index) => (
              <motion.article
                key={index}
                variants={cardVariants}
                whileHover={{
                  y: -3,
                }}
                className="
                  group
                  relative
                  overflow-hidden
                  border
                  border-[#dfd2c1]
                  bg-[#fcfaf5]
                  p-5
                  shadow-[0_8px_28px_rgba(89,50,40,0.05)]
                  transition-shadow
                  duration-300
                  hover:shadow-[0_15px_35px_rgba(89,50,40,0.09)]
                  sm:p-7
                "
              >
                {/* Animated top line */}

                <div
                  className="
                    absolute
                    left-0
                    top-0
                    h-[2px]
                    w-0
                    bg-[#c9a24a]
                    transition-all
                    duration-500
                    group-hover:w-full
                  "
                />

                <div className="flex items-start gap-4">
                  <div
                    className="
                      flex
                      h-11
                      w-11
                      flex-shrink-0
                      items-center
                      justify-center
                      border
                      border-[#d8c59a]
                      bg-[#f5eedf]
                      text-[#76131d]
                      sm:h-12
                      sm:w-12
                    "
                  >
                    {React.cloneElement(item.icon, {
                      className: "w-5 h-5 sm:w-6 sm:h-6",
                      strokeWidth: 1.5,
                    })}
                  </div>

                  <p
                    className="
                      flex-1
                      text-sm
                      leading-7
                      text-[#765c52]
                      sm:text-[15px]
                    "
                  >
                    {item.text}
                  </p>
                </div>
              </motion.article>
            ))}
          </motion.div>
        </div>
      </section>

      {/* =====================================================
          PLATFORM RULES TITLE
      ===================================================== */}

      <section className="px-4 pb-8">
        <motion.div
          initial={{
            opacity: 0,
            y: 25,
          }}
          whileInView={{
            opacity: 1,
            y: 0,
          }}
          viewport={{
            once: true,
          }}
          transition={{
            duration: 0.6,
          }}
          className="mx-auto max-w-5xl text-center"
        >
          <p
            className="
              mb-3
              text-[9px]
              uppercase
              tracking-[0.35em]
              text-[#977e73]
              sm:text-[10px]
            "
          >
            Platform Rules
          </p>

          <h2
            className="
              font-serif
              text-2xl
              font-normal
              leading-snug
              text-[#351216]
              sm:text-3xl
              md:text-4xl
            "
          >
            The use of Platform and/or availing of our Services
            is subject to the following Terms of Use
          </h2>

          <div
            className="
              mt-5
              flex
              items-center
              justify-center
              gap-2
            "
          >
            <span className="h-px w-10 bg-[#c9a24a]" />

            <span className="h-1.5 w-1.5 rounded-full bg-[#c9a24a]" />

            <span className="h-px w-10 bg-[#c9a24a]" />
          </div>
        </motion.div>
      </section>

      {/* =====================================================
          TERMS LIST
      ===================================================== */}

      <section className="px-4 pb-16 sm:pb-20">
        <motion.div
          initial="hidden"
          whileInView="visible"
          viewport={{
            once: true,
            amount: 0.05,
          }}
          variants={{
            hidden: {},
            visible: {
              transition: {
                staggerChildren: 0.06,
              },
            },
          }}
          className="
            mx-auto
            max-w-5xl
            space-y-4
          "
        >
          {termsList.map((term, index) => (
            <motion.article
              key={index}
              variants={cardVariants}
              className="
                group
                relative
                border
                border-[#dfd2c1]
                bg-[#fcfaf5]
                p-5
                shadow-[0_6px_24px_rgba(89,50,40,0.045)]
                transition-all
                duration-300
                hover:shadow-[0_14px_32px_rgba(89,50,40,0.09)]
                sm:p-6
              "
            >
              <div className="flex items-start gap-4">
                {/* Number */}

                <div
                  className="
                    flex
                    h-9
                    w-9
                    flex-shrink-0
                    items-center
                    justify-center
                    border
                    border-[#76131d]
                    bg-[#5d0e16]
                    text-xs
                    font-semibold
                    text-[#c9a24a]
                    transition-colors
                    duration-300
                    group-hover:bg-[#76131d]
                    sm:h-10
                    sm:w-10
                  "
                >
                  {String(index + 1).padStart(2, "0")}
                </div>

                {/* Content */}

                <div className="flex-1">
                  <div className="flex items-start gap-2">
                    <CheckCircle2
                      className="
                        mt-1
                        h-4
                        w-4
                        flex-shrink-0
                        text-[#c9a24a]
                      "
                      strokeWidth={1.6}
                    />

                    <p
                      className="
                        text-sm
                        leading-7
                        text-[#765c52]
                        sm:text-[15px]
                      "
                    >
                      {term}
                    </p>
                  </div>

                  <div
                    className="
                      mt-4
                      h-px
                      origin-left
                      scale-x-0
                      bg-[#eee6dc]
                      transition-transform
                      duration-500
                      group-hover:scale-x-100
                    "
                  />
                </div>
              </div>
            </motion.article>
          ))}
        </motion.div>
      </section>

      {/* =====================================================
          LEGAL FOOTER
      ===================================================== */}

      <section className="px-4 pb-14">
        <motion.div
          initial={{
            opacity: 0,
            scale: 0.97,
          }}
          whileInView={{
            opacity: 1,
            scale: 1,
          }}
          viewport={{
            once: true,
          }}
          transition={{
            duration: 0.6,
          }}
          className="
            relative
            mx-auto
            max-w-5xl
            overflow-hidden
            bg-[#5d0e16]
            p-7
            text-center
            shadow-[0_18px_45px_rgba(89,50,40,0.15)]
            sm:p-10
          "
        >
          <motion.div
            animate={{
              rotate: [0, 10, -10, 0],
            }}
            transition={{
              duration: 5,
              repeat: Infinity,
              ease: "easeInOut",
            }}
            className="inline-flex"
          >
            <Gavel
              className="
                h-8
                w-8
                text-[#c9a24a]
              "
              strokeWidth={1.3}
            />
          </motion.div>

          <h2
            className="
              mt-4
              font-serif
              text-2xl
              text-[#f8f3e9]
              sm:text-3xl
            "
          >
            Your agreement matters
          </h2>

          <p
            className="
              mx-auto
              mt-3
              max-w-2xl
              text-xs
              leading-6
              text-[#eadfd2]
              sm:text-sm
            "
          >
            Please review these Terms of Use carefully before using
            the platform or availing of our services.
          </p>

          <div
            className="
              mt-6
              flex
              items-center
              justify-center
              gap-3
            "
          >
            <span className="h-px w-8 bg-[#c9a24a] sm:w-12" />

            <span
              className="
                text-[8px]
                uppercase
                tracking-[0.3em]
                text-[#c9a24a]
              "
            >
              DARSH
            </span>

            <span className="h-px w-8 bg-[#c9a24a] sm:w-12" />
          </div>
        </motion.div>
      </section>

      {/* =====================================================
          REDUCED MOTION
      ===================================================== */}

      <style>
        {`
          @media (prefers-reduced-motion: reduce) {
            *,
            *::before,
            *::after {
              animation-duration: 0.01ms !important;
              animation-iteration-count: 1 !important;
              transition-duration: 0.01ms !important;
              scroll-behavior: auto !important;
            }
          }
        `}
      </style>
    </main>
  );
};

export default TermsAndConditions;